
def get_users_data():
    return [
  {
    "id": 1,
    "name": "Alice Johnson",
    "email": "alice@email.com",
    "signup": "2024-06-01",
    "status": "Active",
    "plan": "Pro",
    "role": "Admin",
    "lastActive": "2024-06-26 09:21",
    "avatar": "https://ui-avatars.com/api/?name=Alice+Johnson",
  },
  {
    "id": 2,
    "name": "Bob Smith",
    "email": "bob@email.com",
    "signup": "2024-05-28",
    "status": "Pending",
    "plan": "Basic",
    "role": "User",
    "lastActive": "2024-06-24 18:02",
    "avatar": "https://ui-avatars.com/api/?name=Bob+Smith",
  },
  {
    "id": 3,
    "name": "Carla Lopez",
    "email": "carla@email.com",
    "signup": "2024-05-26",
    "status": "Active",
    "plan": "Enterprise",
    "role": "Manager",
    "lastActive": "2024-06-25 15:45",
    "avatar": "https://ui-avatars.com/api/?name=Carla+Lopez",
  },
  {
    "id": 4,
    "name": "David Lee",
    "email": "david@email.com",
    "signup": "2024-05-20",
    "status": "Inactive",
    "plan": "Free",
    "role": "User",
    "lastActive": "2024-06-10 11:12",
    "avatar": "https://ui-avatars.com/api/?name=David+Lee",
  },
  {
    "id": 5,
    "name": "Elena Martín",
    "email": "elena@email.com",
    "signup": "2024-06-15",
    "status": "Active",
    "plan": "Pro",
    "role": "User",
    "lastActive": "2024-06-26 07:44",
    "avatar": "https://ui-avatars.com/api/?name=Elena+Martin",
  },
  {
    "id": 6,
    "name": "Ferran Costa",
    "email": "ferran@email.com",
    "signup": "2024-06-14",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-25 19:10",
    "avatar": "https://ui-avatars.com/api/?name=Ferran+Costa",
  },
  {
    "id": 7,
    "name": "Gabriela Sánchez",
    "email": "gabriela@email.com",
    "signup": "2024-06-13",
    "status": "Pending",
    "plan": "Basic",
    "role": "Manager",
    "lastActive": "2024-06-23 13:33",
    "avatar": "https://ui-avatars.com/api/?name=Gabriela+Sanchez",
  },
  {
    "id": 8,
    "name": "Hugo Romero",
    "email": "hugo@email.com",
    "signup": "2024-05-29",
    "status": "Inactive",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-21 15:01",
    "avatar": "https://ui-avatars.com/api/?name=Hugo+Romero",
  },
  {
    "id": 9,
    "name": "Isabel Pérez",
    "email": "isabel@email.com",
    "signup": "2024-06-03",
    "status": "Active",
    "plan": "Pro",
    "role": "Admin",
    "lastActive": "2024-06-26 10:45",
    "avatar": "https://ui-avatars.com/api/?name=Isabel+Perez",
  },
  {
    "id": 10,
    "name": "Javier Moya",
    "email": "javier@email.com",
    "signup": "2024-06-08",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-26 09:10",
    "avatar": "https://ui-avatars.com/api/?name=Javier+Moya",
  },
  {
    "id": 11,
    "name": "Karla Fernández",
    "email": "karla@email.com",
    "signup": "2024-06-05",
    "status": "Pending",
    "plan": "Enterprise",
    "role": "User",
    "lastActive": "2024-06-20 11:00",
    "avatar": "https://ui-avatars.com/api/?name=Karla+Fernandez",
  },
  {
    "id": 12,
    "name": "Luis Navarro",
    "email": "luis@email.com",
    "signup": "2024-05-31",
    "status": "Active",
    "plan": "Manager",
    "role": "Manager",
    "lastActive": "2024-06-25 17:02",
    "avatar": "https://ui-avatars.com/api/?name=Luis+Navarro",
  },
  {
    "id": 13,
    "name": "María Gómez",
    "email": "maria@email.com",
    "signup": "2024-06-18",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-26 08:33",
    "avatar": "https://ui-avatars.com/api/?name=Maria+Gomez",
  },
  {
    "id": 14,
    "name": "Néstor Ibáñez",
    "email": "nestor@email.com",
    "signup": "2024-06-11",
    "status": "Inactive",
    "plan": "Basic",
    "role": "Admin",
    "lastActive": "2024-06-16 14:21",
    "avatar": "https://ui-avatars.com/api/?name=Nestor+Ibanez",
  },
  {
    "id": 15,
    "name": "Olga Ramos",
    "email": "olga@email.com",
    "signup": "2024-06-22",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-26 11:20",
    "avatar": "https://ui-avatars.com/api/?name=Olga+Ramos",
  },
  {
    "id": 16,
    "name": "Pablo Torres",
    "email": "pablo@email.com",
    "signup": "2024-05-23",
    "status": "Active",
    "plan": "Pro",
    "role": "User",
    "lastActive": "2024-06-25 16:11",
    "avatar": "https://ui-avatars.com/api/?name=Pablo+Torres",
  },
  {
    "id": 17,
    "name": "Quim Font",
    "email": "quim@email.com",
    "signup": "2024-05-24",
    "status": "Inactive",
    "plan": "Manager",
    "role": "Manager",
    "lastActive": "2024-06-22 18:45",
    "avatar": "https://ui-avatars.com/api/?name=Quim+Font",
  },
  {
    "id": 18,
    "name": "Raquel Alonso",
    "email": "raquel@email.com",
    "signup": "2024-06-02",
    "status": "Active",
    "plan": "Enterprise",
    "role": "User",
    "lastActive": "2024-06-26 10:01",
    "avatar": "https://ui-avatars.com/api/?name=Raquel+Alonso",
  },
  {
    "id": 19,
    "name": "Samuel Vidal",
    "email": "samuel@email.com",
    "signup": "2024-05-27",
    "status": "Pending",
    "plan": "Pro",
    "role": "User",
    "lastActive": "2024-06-24 12:45",
    "avatar": "https://ui-avatars.com/api/?name=Samuel+Vidal",
  },
  {
    "id": 20,
    "name": "Teresa Gil",
    "email": "teresa@email.com",
    "signup": "2024-06-12",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-25 20:10",
    "avatar": "https://ui-avatars.com/api/?name=Teresa+Gil",
  },
  {
    "id": 21,
    "name": "Ursula Montes",
    "email": "ursula@email.com",
    "signup": "2024-06-10",
    "status": "Active",
    "plan": "Basic",
    "role": "Admin",
    "lastActive": "2024-06-24 21:30",
    "avatar": "https://ui-avatars.com/api/?name=Ursula+Montes",
  },
  {
    "id": 22,
    "name": "Víctor Saez",
    "email": "victor@email.com",
    "signup": "2024-06-08",
    "status": "Inactive",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-19 17:50",
    "avatar": "https://ui-avatars.com/api/?name=Victor+Saez",
  },
  {
    "id": 23,
    "name": "Wendy González",
    "email": "wendy@email.com",
    "signup": "2024-06-17",
    "status": "Pending",
    "plan": "Pro",
    "role": "User",
    "lastActive": "2024-06-23 09:05",
    "avatar": "https://ui-avatars.com/api/?name=Wendy+Gonzalez",
  },
  {
    "id": 24,
    "name": "Xavi Ruiz",
    "email": "xavi@email.com",
    "signup": "2024-05-30",
    "status": "Active",
    "plan": "Manager",
    "role": "Manager",
    "lastActive": "2024-06-25 13:00",
    "avatar": "https://ui-avatars.com/api/?name=Xavi+Ruiz",
  },
  {
    "id": 25,
    "name": "Yolanda Díaz",
    "email": "yolanda@email.com",
    "signup": "2024-06-21",
    "status": "Active",
    "plan": "Enterprise",
    "role": "Admin",
    "lastActive": "2024-06-26 09:55",
    "avatar": "https://ui-avatars.com/api/?name=Yolanda+Diaz",
  },
  {
    "id": 26,
    "name": "Zoe Romero",
    "email": "zoe@email.com",
    "signup": "2024-06-19",
    "status": "Active",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-26 08:22",
    "avatar": "https://ui-avatars.com/api/?name=Zoe+Romero",
  },
  {
    "id": 27,
    "name": "Ana Peña",
    "email": "ana@email.com",
    "signup": "2024-05-22",
    "status": "Active",
    "plan": "Pro",
    "role": "Manager",
    "lastActive": "2024-06-26 10:18",
    "avatar": "https://ui-avatars.com/api/?name=Ana+Peña",
  },
  {
    "id": 28,
    "name": "Bruno Ortega",
    "email": "bruno@email.com",
    "signup": "2024-06-06",
    "status": "Inactive",
    "plan": "Basic",
    "role": "User",
    "lastActive": "2024-06-16 13:33",
    "avatar": "https://ui-avatars.com/api/?name=Bruno+Ortega",
  },
  {
    "id": 29,
    "name": "Celia Duarte",
    "email": "celia@email.com",
    "signup": "2024-06-16",
    "status": "Pending",
    "plan": "User",
    "role": "User",
    "lastActive": "2024-06-23 22:12",
    "avatar": "https://ui-avatars.com/api/?name=Celia+Duarte",
  },
  {
    "id": 30,
    "name": "Diego Serrano",
    "email": "diego@email.com",
    "signup": "2024-06-09",
    "status": "Active",
    "plan": "Enterprise",
    "role": "Admin",
    "lastActive": "2024-06-26 11:45",
    "avatar": "https://ui-avatars.com/api/?name=Diego+Serrano",
  },
]